backend:
  name: git-gateway
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - name: "affiliate"
    label: "Produk Affiliate"
    folder: "jasa/affiliate"
    extension: "json"
    create: true
    slug: "{{title}}"
    fields:
      - {label: "Nama Produk", name: "title", widget: "string"}
      - {label: "Harga", name: "price", widget: "string"}
      - {label: "Link Affiliate", name: "link", widget: "string"}
      - {label: "Foto Produk", name: "image", widget: "image"}

  - name: "jasa_coding"
    label: "Layanan Jasa Coding"
    file: "jasa/data.json" # Kita pakai satu file untuk semua jasa coding
    fields:
      - name: "digital"
        label: "Daftar Jasa"
        widget: "list"
        fields:
          - {label: "ID (web-dev/bot-dev)", name: "id", widget: "string"}
          - {label: "Judul", name: "title", widget: "string"}
          - {label: "Deskripsi", name: "desc", widget: "text"}
          - {label: "Detail HTML", name: "detail", widget: "text"}
          - {label: "Harga", name: "price", widget: "string"}
          - {label: "Link WA", name: "waLink", widget: "string"}