name: Push to HostData

on:
  push:
    branches:
      - main  # Pastikan nama branch kamu 'main', kalau 'master' ganti jadi master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 🚀 Sync files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: server4.hostdata.id
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: domains/viel.my.id/public_html/